version: "2"

services:

  mydb:    
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db/var/lib/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"    
    environment:
      # set same as db credentials and dbname
      - DB_HOST=mydb
      - DB_PORT_NUMBER=3306
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(mydb:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  


 
